import React, { Component } from "react";

export default class PublicationsImg extends Component {
  render() {
    const theme = this.props.theme;
    return (
      <svg
        id="publications-img"
        data-name="Layer 1"
        xmlns="http://www.w3.org/2000/svg"
        width="800"
        height="600"
        viewBox="0 0 800 600"
      >
        <title>Publications</title>
        {/* Background shapes */}
        <rect
          x="100"
          y="150"
          width="200"
          height="250"
          rx="8"
          fill={theme.imageHighlight}
          opacity="0.1"
        />
        <rect
          x="320"
          y="120"
          width="200"
          height="280"
          rx="8"
          fill={theme.imageHighlight}
          opacity="0.15"
        />
        <rect
          x="540"
          y="180"
          width="200"
          height="220"
          rx="8"
          fill={theme.imageHighlight}
          opacity="0.1"
        />

        {/* Document/Paper shapes */}
        <rect
          x="120"
          y="170"
          width="160"
          height="220"
          rx="4"
          fill="none"
          stroke={theme.imageHighlight}
          strokeWidth="3"
          opacity="0.6"
        />
        <line
          x1="140"
          y1="200"
          x2="240"
          y2="200"
          stroke={theme.imageHighlight}
          strokeWidth="2"
          opacity="0.5"
        />
        <line
          x1="140"
          y1="230"
          x2="240"
          y2="230"
          stroke={theme.imageHighlight}
          strokeWidth="2"
          opacity="0.5"
        />
        <line
          x1="140"
          y1="260"
          x2="200"
          y2="260"
          stroke={theme.imageHighlight}
          strokeWidth="2"
          opacity="0.5"
        />

        <rect
          x="340"
          y="140"
          width="160"
          height="250"
          rx="4"
          fill="none"
          stroke={theme.imageHighlight}
          strokeWidth="3"
          opacity="0.6"
        />
        <line
          x1="360"
          y1="170"
          x2="460"
          y2="170"
          stroke={theme.imageHighlight}
          strokeWidth="2"
          opacity="0.5"
        />
        <line
          x1="360"
          y1="200"
          x2="460"
          y2="200"
          stroke={theme.imageHighlight}
          strokeWidth="2"
          opacity="0.5"
        />
        <line
          x1="360"
          y1="230"
          x2="420"
          y2="230"
          stroke={theme.imageHighlight}
          strokeWidth="2"
          opacity="0.5"
        />

        <rect
          x="560"
          y="200"
          width="160"
          height="190"
          rx="4"
          fill="none"
          stroke={theme.imageHighlight}
          strokeWidth="3"
          opacity="0.6"
        />
        <line
          x1="580"
          y1="230"
          x2="680"
          y2="230"
          stroke={theme.imageHighlight}
          strokeWidth="2"
          opacity="0.5"
        />
        <line
          x1="580"
          y1="260"
          x2="680"
          y2="260"
          stroke={theme.imageHighlight}
          strokeWidth="2"
          opacity="0.5"
        />
        <line
          x1="580"
          y1="290"
          x2="640"
          y2="290"
          stroke={theme.imageHighlight}
          strokeWidth="2"
          opacity="0.5"
        />

        {/* Decorative circles */}
        <circle
          cx="200"
          cy="100"
          r="30"
          fill={theme.imageHighlight}
          opacity="0.1"
        />
        <circle
          cx="420"
          cy="80"
          r="25"
          fill={theme.imageHighlight}
          opacity="0.15"
        />
        <circle
          cx="640"
          cy="120"
          r="20"
          fill={theme.imageHighlight}
          opacity="0.1"
        />
      </svg>
    );
  }
}
